grocery_list = list()
grocery_list.append("Milk")
grocery_list.append("Bread")
grocery_list.append("Eggs")
grocery_list.append("Peanut Butter")
grocery_list.append("Jelly")
print(grocery_list)
grocery_list.insert(3,"Almond Butter")
grocery_list.remove("Jelly")
grocery_list.append("coffee")
print(grocery_list)